config/routes.rb
Vpac::Application.routes.draw do
  resources :community_scores

  resources :attended_shows do
    collection { post :import }
  end

  resources :members

  resources :publicity_topics

  resources :member_groups do
    collection { post :import }
  end

  resources :board_members
  resources :current_board, controller: :board_members, only: [:index]

  resources :acfee_topics
  resources :anchor_link_topics

  root 'static_pages#home'

  match '/mission', to: 'static_pages#mission', via: 'get'
  match '/history', to: 'static_pages#history', via: 'get'

  match 'reserve_space', to: 'static_pages#reserve_space', via: 'get'
  match 'publicity_help', to: 'publicity_topics#index', via: 'get'
  match '/acfee_help', to: 'acfee_topics#index', via: 'get'
  match '/anchor_link_help', to: 'anchor_link_topics#index', via: 'get'

  match '/calendar', to: 'static_pages#calendar', via: 'get'
  match '/auditions', to: 'static_pages#auditions', via: 'get'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/main_attraction', to: 'static_pages#main_attraction', via: 'get'
  match '/encore', to: 'static_pages#encore', via: 'get'

  match '/media', to: 'static_pages#media', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/nomination', to: 'static_pages#nomination', via: 'get'

  match '/send_contact_email', to: 'static_pages#send_contact_email', via: 'post'
  match '/send_nomination_email', to: 'static_pages#send_nomination_email', via: 'post'

  match '/community', to: 'community#index', via: 'get'
  match '/csv', to: 'member_groups#csv', via: 'post'
  match '/text', to: 'member_groups#text', via: 'post'

end

app/models/member_group.rb
class MemberGroup < ActiveRecord::Base
  has_and_belongs_to_many :members
  has_many :attended_shows
  has_one :community_score

  before_save :calculate_community_score
  before_update :calculate_community_score

  def self.make_csv(file, options = {})
    f = File.open(file.path, 'r')

    csv = CSV.generate(options) do |csv|
      csv << %w(Email Name)

      f.each_line do |line|
        words = line.split(' ')
        words = [ words[0], words[1..words.count - 1].join(' ') ]
        csv << words
      end
    end

    f.close

    csv
  end

  def self.make_text(file)
    f = File.open('file.txt', 'w+')

    CSV.foreach(file.path, headers: true) do |row|
      name = row['Name']
      email = row['Email']

      puts name
      puts "#{email} #{name}\n"

      f.write("#{email} #{name}\n")
    end

    f
  end

  def self.import(group_id, file)
    group = MemberGroup.find group_id

    CSV.foreach(file.path, headers: true) do |row|
      name = row['Name']
      email = row['Email']

      member = Member.find_by email: email.downcase
      member ||= Member.create(name: name, email: email)

      group.members.push(member) unless group.members.exists?(member)
    end
  end

  def calculate_community_score
    group_count = self.members.count * 1.0 # To make sure it's not integer division
    total_percentage_attended = 0
    avg_percentage_attended = 0
    shows_attended = 0
    number_score = 0
    shows_counted = [ ]

    AttendedShow.all.each do |show|
      if !shows_counted.include?(show.title)
        if show.member_group.eql?(self) && !show.host_org.eql?(self.name)
          shows_attended += 1
          total_percentage_attended += show.members.count / group_count

          shows_counted.push(show.title)
        end
      end
    end

    avg_percentage_attended = total_percentage_attended / shows_counted.count unless shows_counted.count == 0
    number_score = ((2.0 / 3) * avg_percentage_attended + (1.0 / 3) * shows_attended) unless avg_percentage_attended == 0 || shows_attended == 0

    if (self.community_score.nil?)
      self.community_score = CommunityScore.create(member_group: self, number_score: number_score)
    else
      self.community_score.number_score = number_score
      self.community_score.save
    end
  end
end

app/controllers/member_groups_controller.rb
class MemberGroupsController < ApplicationController
  before_action :set_member_group, only: [:show, :edit, :update, :destroy]

  # GET /member_groups
  # GET /member_groups.json
  def index
    @member_groups = ContentfulClient.instance.member_groups.sort_by do |member_group|
      member_group.name.gsub(/\bThe \b/, '')
    end
  end

  # GET /member_groups/1
  # GET /member_groups/1.json
  def show
  end

  # GET /member_groups/new
  def new
    @member_group = MemberGroup.new
  end

  # GET /member_groups/1/edit
  def edit
  end

  # POST /member_groups
  # POST /member_groups.json
  def create
    @member_group = MemberGroup.new(member_group_params)

    respond_to do |format|
      if @member_group.save
        format.html { redirect_to @member_group, notice: 'Member group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @member_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_groups/1
  # PATCH/PUT /member_groups/1.json
  def update
    respond_to do |format|
      if @member_group.update(member_group_params)
        format.html { redirect_to @member_group, notice: 'Member group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_groups/1
  # DELETE /member_groups/1.json
  def destroy
    @member_group.destroy
    respond_to do |format|
      format.html { redirect_to member_groups_url }
      format.json { head :no_content }
    end
  end

  def text
    f = MemberGroup.make_text(params[:file])
    send_file f
    f.close
  end

  def csv
    send_data MemberGroup.make_csv(params[:file])
  end

  def import
    MemberGroup.import(params[:group_name], params[:file])
    redirect_to members_path, notice: 'Members imported.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_group
      @member_group = MemberGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_group_params
      params.require(:member_group).permit(:name, :photo_url, :primary_contact, :email, :description, :website_url)
    end
end

app/helpers/member_groups_helper.rb
module MemberGroupsHelper
end

app/views/member_groups/_form.html.erb
<%= form_for(@member_group) do |f| %>
  <% if @member_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_group.errors.count, "error") %> prohibited this member_group from being saved:</h2>

      <ul>
      <% @member_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_groups/edit.html.erb
<h1>Editing member_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @member_group %> |
<%= link_to 'Back', member_groups_path %>

app/views/member_groups/index.html.erb
<% provide(:title, 'Member Groups') %>
<% provide(:jumbotron_class, 'about') %>

<%= render 'layouts/jumbotron' %>

<div class="container-content">
  <div class="container">
    <% @member_groups.each do |member_group| %>
      <div class="row member-group-row">
        <div class="col-xs-12 col-sm-5">
          <%= image_tag member_group.image.image_url, alt: "Photo of #{ member_group.name }", class: 'img-rounded member-group-photo img-responsive' %>
        </div>

        <div class="col-xs-12 col-sm-7">
          <div class="caption">
            <h3 class="top-column-header">Name</h3>
            <p class="lead"><%= link_to member_group.name, member_group.website, target: '_blank' %></p>

            <h3 class="column-header">Description</h3>
            <p class="lead"><%= member_group.description %></p>

            <!--<p class="lead"><#%= mail_to board_member.email, "Email #{ board_member.name.split(' ')[0] }" %></p>-->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/member_groups/new.html.erb
<h1>New member_group</h1>

<%= render 'form' %>

<%= link_to 'Back', member_groups_path %>

app/views/member_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member_group.name %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @member_group.photo_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @member_group.description %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @member_group.website_url %>
</p>

<p>
  <strong>Members:</strong><br />
  <% @member_group.members.each do |member| %>
    <%= member.name %><br />
  <% end %>
</p>

<p>
  <strong>Attended Shows:</strong><br />
  <% @member_group.attended_shows.each do |show| %>
    <% if (!show.host_org.eql?(@member_group.name)) %>
      <%= show.title %><br />
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_member_group_path(@member_group) %> |
<%= link_to 'Back', member_groups_path %>