config/routes.rb
Vpac::Application.routes.draw do
  resources :community_scores

  resources :attended_shows do
    collection { post :import }
  end

  resources :members

  resources :publicity_topics

  resources :member_groups do
    collection { post :import }
  end

  resources :board_members
  resources :current_board, controller: :board_members, only: [:index]

  resources :acfee_topics
  resources :anchor_link_topics

  root 'static_pages#home'

  match '/mission', to: 'static_pages#mission', via: 'get'
  match '/history', to: 'static_pages#history', via: 'get'

  match 'reserve_space', to: 'static_pages#reserve_space', via: 'get'
  match 'publicity_help', to: 'publicity_topics#index', via: 'get'
  match '/acfee_help', to: 'acfee_topics#index', via: 'get'
  match '/anchor_link_help', to: 'anchor_link_topics#index', via: 'get'

  match '/calendar', to: 'static_pages#calendar', via: 'get'
  match '/auditions', to: 'static_pages#auditions', via: 'get'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/main_attraction', to: 'static_pages#main_attraction', via: 'get'
  match '/encore', to: 'static_pages#encore', via: 'get'

  match '/media', to: 'static_pages#media', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/nomination', to: 'static_pages#nomination', via: 'get'

  match '/send_contact_email', to: 'static_pages#send_contact_email', via: 'post'
  match '/send_nomination_email', to: 'static_pages#send_nomination_email', via: 'post'

  match '/community', to: 'community#index', via: 'get'
  match '/csv', to: 'member_groups#csv', via: 'post'
  match '/text', to: 'member_groups#text', via: 'post'

end

app/models/community_score.rb
class CommunityScore < ActiveRecord::Base
  belongs_to :member_group
end

app/controllers/community_scores_controller.rb
class CommunityScoresController < ApplicationController
  before_action :set_community_score, only: [:show, :edit, :update, :destroy]

  # GET /community_scores
  # GET /community_scores.json
  def index
    @community_scores = CommunityScore.all.sort_by do |score|
      -score.number_score
    end
  end

  # GET /community_scores/1
  # GET /community_scores/1.json
  def show
  end

  # GET /community_scores/new
  def new
    @community_score = CommunityScore.new
  end

  # GET /community_scores/1/edit
  def edit
  end

  # POST /community_scores
  # POST /community_scores.json
  def create
    @community_score = CommunityScore.new(community_score_params)

    respond_to do |format|
      if @community_score.save
        format.html { redirect_to @community_score, notice: 'Community score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @community_score }
      else
        format.html { render action: 'new' }
        format.json { render json: @community_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_scores/1
  # PATCH/PUT /community_scores/1.json
  def update
    respond_to do |format|
      if @community_score.update(community_score_params)
        format.html { redirect_to @community_score, notice: 'Community score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @community_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_scores/1
  # DELETE /community_scores/1.json
  def destroy
    @community_score.destroy
    respond_to do |format|
      format.html { redirect_to community_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_score
      @community_score = CommunityScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_score_params
      params.require(:community_score).permit(:school_year, :member_group_id, :number_score)
    end
end

app/helpers/community_scores_helper.rb
module CommunityScoresHelper
end

app/views/community_scores/_form.html.erb
<%= form_for(@community_score) do |f| %>
  <% if @community_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community_score.errors.count, "error") %> prohibited this community_score from being saved:</h2>

      <ul>
      <% @community_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_year %><br>
    <%= f.text_field :school_year %>
  </div>
  <div class="field">
    <%= f.label :member_group_id %><br>
    <%= f.text_field :member_group_id %>
  </div>
  <div class="field">
    <%= f.label :number_score %><br>
    <%= f.text_field :number_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/community_scores/edit.html.erb
<h1>Editing community_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @community_score %> |
<%= link_to 'Back', community_scores_path %>

app/views/community_scores/index.html.erb
<h1>Listing community_scores</h1>

<table>
  <thead>
    <tr>
      <th>School year</th>
      <th>Member group</th>
      <th>Number score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @community_scores.each do |community_score| %>
      <tr>
        <td><%= community_score.school_year %></td>
        <td><%= community_score.member_group.name %></td>
        <td><%= number_with_precision(community_score.number_score, precision: 2) %></td>
        <td><%= link_to 'Show', community_score %></td>
        <td><%= link_to 'Edit', edit_community_score_path(community_score) %></td>
        <td><%= link_to 'Destroy', community_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community score', new_community_score_path %>

app/views/community_scores/new.html.erb
<h1>New community_score</h1>

<%= render 'form' %>

<%= link_to 'Back', community_scores_path %>

app/views/community_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School year:</strong>
  <%= @community_score.school_year %>
</p>

<p>
  <strong>Member group:</strong>
  <%= @community_score.member_group.name %>
</p>

<p>
  <strong>Number score:</strong>
  <%= @community_score.number_score %>
</p>

<%= link_to 'Edit', edit_community_score_path(@community_score) %> |
<%= link_to 'Back', community_scores_path %>