config/routes.rb
Vpac::Application.routes.draw do
  resources :community_scores

  resources :attended_shows do
    collection { post :import }
  end

  resources :members

  resources :publicity_topics

  resources :member_groups do
    collection { post :import }
  end

  resources :board_members
  resources :current_board, controller: :board_members, only: [:index]

  resources :acfee_topics
  resources :anchor_link_topics

  root 'static_pages#home'

  match '/mission', to: 'static_pages#mission', via: 'get'
  match '/history', to: 'static_pages#history', via: 'get'

  match 'reserve_space', to: 'static_pages#reserve_space', via: 'get'
  match 'publicity_help', to: 'publicity_topics#index', via: 'get'
  match '/acfee_help', to: 'acfee_topics#index', via: 'get'
  match '/anchor_link_help', to: 'anchor_link_topics#index', via: 'get'

  match '/calendar', to: 'static_pages#calendar', via: 'get'
  match '/auditions', to: 'static_pages#auditions', via: 'get'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/main_attraction', to: 'static_pages#main_attraction', via: 'get'
  match '/encore', to: 'static_pages#encore', via: 'get'

  match '/media', to: 'static_pages#media', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/nomination', to: 'static_pages#nomination', via: 'get'

  match '/send_contact_email', to: 'static_pages#send_contact_email', via: 'post'
  match '/send_nomination_email', to: 'static_pages#send_nomination_email', via: 'post'

  match '/community', to: 'community#index', via: 'get'
  match '/csv', to: 'member_groups#csv', via: 'post'
  match '/text', to: 'member_groups#text', via: 'post'

end

app/models/attended_show.rb
class AttendedShow < ActiveRecord::Base
  has_and_belongs_to_many :members
  belongs_to :member_group

  def self.import(title, host_org, file)
    group_name = MemberGroup.find(host_org).name

    MemberGroup.all.each do |group|
      if (!group.name.eql?(group_name))
        show = AttendedShow.new(title: title, host_org: group_name, school_year: '2013-2014', member_group: group)

        CSV.foreach(file.path, headers: true) do |row|
          email = row['Campus Email']

          member = Member.find_by email: email.downcase unless email.nil?

          if (!member.nil? && member.member_groups.exists?(group))
            member.attended_shows.push(show)
            group.calculate_community_score
          end
        end
      end
    end
  end
end

app/controllers/attended_shows_controller.rb
class AttendedShowsController < ApplicationController
  before_action :set_attended_show, only: [:show, :edit, :update, :destroy]

  # GET /attended_shows
  # GET /attended_shows.json
  def index
    @attended_shows = AttendedShow.all
  end

  # GET /attended_shows/1
  # GET /attended_shows/1.json
  def show
  end

  # GET /attended_shows/new
  def new
    @attended_show = AttendedShow.new
  end

  # GET /attended_shows/1/edit
  def edit
  end

  # POST /attended_shows
  # POST /attended_shows.json
  def create
    @attended_show = AttendedShow.new(attended_show_params)

    respond_to do |format|
      if @attended_show.save
        format.html { redirect_to @attended_show, notice: 'Attended show was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attended_show }
      else
        format.html { render action: 'new' }
        format.json { render json: @attended_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attended_shows/1
  # PATCH/PUT /attended_shows/1.json
  def update
    respond_to do |format|
      if @attended_show.update(attended_show_params)
        format.html { redirect_to @attended_show, notice: 'Attended show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attended_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attended_shows/1
  # DELETE /attended_shows/1.json
  def destroy
    @attended_show.destroy
    respond_to do |format|
      format.html { redirect_to attended_shows_url }
      format.json { head :no_content }
    end
  end

  def import
    AttendedShow.import(params[:title], params[:host_org], params[:file])
    redirect_to members_path, notice: 'Show imported.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attended_show
      @attended_show = AttendedShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attended_show_params
      params.require(:attended_show).permit(:title, :school_year, :host_org)
    end
end

app/helpers/attended_shows_helper.rb
module AttendedShowsHelper
end

app/views/attended_shows/_form.html.erb
<%= form_for(@attended_show) do |f| %>
  <% if @attended_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attended_show.errors.count, "error") %> prohibited this attended_show from being saved:</h2>

      <ul>
      <% @attended_show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :school_year %><br>
    <%= f.text_field :school_year %>
  </div>
  <div class="field">
    <%= f.label :host_org %><br>
    <%= f.text_field :host_org %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attended_shows/edit.html.erb
<h1>Editing attended_show</h1>

<%= render 'form' %>

<%= link_to 'Show', @attended_show %> |
<%= link_to 'Back', attended_shows_path %>

app/views/attended_shows/index.html.erb
<h1>Listing attended_shows</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>School year</th>
      <th>Host org</th>
      <th>Attending Org</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attended_shows.each do |attended_show| %>
      <tr>
        <td><%= attended_show.title %></td>
        <td><%= attended_show.school_year %></td>
        <td><%= attended_show.host_org %></td>
        <td><%= attended_show.member_group.name %></td>
        <td><%= link_to 'Show', attended_show %></td>
        <td><%= link_to 'Edit', edit_attended_show_path(attended_show) %></td>
        <td><%= link_to 'Destroy', attended_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attended show', new_attended_show_path %>

app/views/attended_shows/new.html.erb
<h1>New attended_show</h1>

<%= render 'form' %>

<%= link_to 'Back', attended_shows_path %>

app/views/attended_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @attended_show.title %>
</p>

<p>
  <strong>School year:</strong>
  <%= @attended_show.school_year %>
</p>

<p>
  <strong>Host org:</strong>
  <%= @attended_show.host_org %>
</p>

<p>
  <strong>Attended Org:</strong>
  <%= @attended_show.member_group.name %>
</p>

<p>
  <strong>Students Attended:</strong>
  <%= @attended_show.members.count %><br />
  <% @attended_show.members.each do |member| %>
    <%= member.name %><br />
  <% end %>
</p>

<%= link_to 'Edit', edit_attended_show_path(@attended_show) %> |
<%= link_to 'Back', attended_shows_path %>