config/routes.rb
Vpac::Application.routes.draw do
  resources :community_scores

  resources :attended_shows do
    collection { post :import }
  end

  resources :members

  resources :publicity_topics

  resources :member_groups do
    collection { post :import }
  end

  resources :board_members
  resources :current_board, controller: :board_members, only: [:index]

  resources :acfee_topics
  resources :anchor_link_topics

  root 'static_pages#home'

  match '/mission', to: 'static_pages#mission', via: 'get'
  match '/history', to: 'static_pages#history', via: 'get'

  match 'reserve_space', to: 'static_pages#reserve_space', via: 'get'
  match 'publicity_help', to: 'publicity_topics#index', via: 'get'
  match '/acfee_help', to: 'acfee_topics#index', via: 'get'
  match '/anchor_link_help', to: 'anchor_link_topics#index', via: 'get'

  match '/calendar', to: 'static_pages#calendar', via: 'get'
  match '/auditions', to: 'static_pages#auditions', via: 'get'
  match '/spotlight', to: 'static_pages#spotlight', via: 'get'
  match '/main_attraction', to: 'static_pages#main_attraction', via: 'get'
  match '/encore', to: 'static_pages#encore', via: 'get'

  match '/media', to: 'static_pages#media', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/nomination', to: 'static_pages#nomination', via: 'get'

  match '/send_contact_email', to: 'static_pages#send_contact_email', via: 'post'
  match '/send_nomination_email', to: 'static_pages#send_nomination_email', via: 'post'

  match '/community', to: 'community#index', via: 'get'
  match '/csv', to: 'member_groups#csv', via: 'post'
  match '/text', to: 'member_groups#text', via: 'post'

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_and_belongs_to_many :attended_shows
  has_and_belongs_to_many :member_groups

  before_validation 'lowercase_email'

  # It's honestly not completely possible to validate this completely. A student could have
  # one email on one listserv and one email on another. Name can't be validated either because
  # two students could have the same name, or a student could have one name or one listserv and one on
  # another, e.g. "Anna Bloemer" and "Annie Bloemer"
  validates_uniqueness_of :email

  def lowercase_email
    self.email.downcase!
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Member Groups:</strong>
  <% @member.member_groups.each do |group| %>
    <%= group.name %><br />
  <% end %>
</p>

<p>
  <strong>Shows Attended:</strong><br />
  <% @member.attended_shows.each do |show| %>
    <%= show.title %><br />

  <% end %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>